[[entries]]
name = "Amazon"
prefix = "e "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/amazon.svg"
url = "https://www.amazon.eg/s?k=%TERM%"

[[entries]]
name = "Arch Wiki"
prefix = "a "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/archlinux.svg"
url = "https://wiki.archlinux.org/index.php?search=%TERM%"

[[entries]]
name = "ChatGPT"
prefix = "c "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/chatgpt.svg"
url = "https://chat.openai.com/?q=%TERM%"

[[entries]]
name = "Freepik"
prefix = "f "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/freepik.svg"
url = "https://www.freepik.com/search?format=search&selection=1&orientation=landscape&query=%TERM%"

[[entries]]
name = "GitHub"
prefix = "git "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/github.svg"
url = "https://github.com/search?utf8=âœ“&q=%TERM%"

[[entries]]
name = "Google"
prefix = "g "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/google.svg"
url = "https://www.google.com/search?q=%TERM%"

[[entries]]
name = "Grok"
prefix = "k "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/grok.svg"
url = "https://grok.com?q=%TERM%"

[[entries]]
name = "Iconscout"
prefix = "i "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/iconscout.svg"
url = "https://iconscout.com/icons/%TERM%?price=free"

[[entries]]
name = "Jumia"
prefix = "j "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/jumia.svg"
url = "https://www.jumia.com.eg/ar/catalog/?q=%TERM%"

[[entries]]
name = "MDN"
prefix = "m "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/mdn.svg"
url = "https://developer.mozilla.org/en-US/search?q=%TERM%"

[[entries]]
name = "NPM"
prefix = "npm "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/npm.svg"
url = "https://www.npmjs.com/search?q=%TERM%"

[[entries]]
name = "Noon"
prefix = "n "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/noon.svg"
url = "https://www.noon.com/egypt-ar/search/?q=%TERM%"

[[entries]]
name = "Reddit"
prefix = "r "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/reddit.svg"
url = "https://www.reddit.com/search/?q=%TERM%"

[[entries]]
name = "Tailwind"
prefix = "t "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/tailwind.svg"
url = "https://tailwindcss.com/docs/%TERM%"

[[entries]]
name = "Urban Dictionary"
prefix = "u "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/Urban-Dictionary.svg"
url = "https://www.urbandictionary.com/define.php?term=%TERM%"

[[entries]]
name = "Wikipedia"
prefix = "w "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/wikipedia.svg"
url = "https://en.wikipedia.org/wiki/Special:Search?search=%TERM%"

[[entries]]
name = "YouTube"
prefix = "y "
icon = "/home/muhammad/DotFiles/.config/elephant/icons/youtube.svg"
url = "https://www.youtube.com/results?search_query=%TERM%"
