[greenclip]
  history_file = "~/.local/share/greenclip.history"
  enable_image_support = true
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 10000
  max_selection_size_bytes = 0
  trim_space_from_selection = true
  use_primary_selection_as_input = false
  blacklisted_applications = []
  static_history = []
